server:
    port: 8191
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: springstudent
    password: springstudent
    
    jpa:
        hibernate:
          ddl-auto: update



