server:
    port: 8191
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
        ddl-auto: create



